#!/bin/bash
#SBATCH --verbose --job-name=expCloudML --output=out.result.%j --mem=250GB --nodes=1 --cpus-per-task=28 --time=00:60:00 --gres=gpu:k80:4
module load python3/intel/3.6.3 cuda/9.0.176 nccl/cuda9.0/2.4.2
source ~/project3/torchtext_env/py3.6.3/bin/activate
pip install bayesian-optimization
python train2.py -e 2 -l 0.00037 -b 25 -hi 275 -c False
